### ISSUE TITLE
No output file of Benchmarking?

### ISSUE THREAD

**Issue by kyoheikoyama** [psipred/DeepCov#1]
Hello. Thank you very much for your great work! I really enjoyed your research.

I have followed the README and I was able to successfully run  `setup.sh ` and `./deepcov.sh -i test/example_io/1guuA.aln -o test/test.out`. That was great. Thank you.
However, when doing `Benchmarking scripts`, 'all_windowsize_results_MEAN_covar_min6_max11.txt' does not show any results. It only shows `window	L	L/2	L/5	L/10	L=100` and receptive field sizes.

Could you describe the potential reasons?

**Comment by shaunmk** [comment]
Hi,

Without more information it's hard to say, but the missing values are added in by an R script (bench_plots_and_stats_covar_pairfreq.R). It sounds like that script is failing to produce output.

In `run_all_covar_rawfreq.sh` you can see that the script produces three stderr files: `bench1.err`, `bench2.err` and `bench3.err`. Can you paste the contents of these 3 files?

**Comment by kyoheikoyama** [comment]
Hi, Shaun 

Thank you very much for your reply. 
I understood places of error file and log file.

My code finally works after I installed beanplot and I could reproduce the result in the paper.
Thank you very much again!!!

Kyohei

**Comment by shaunmk** [comment]
Great to hear you got that resolved. It's probably worth me adding that package to the list of dependencies.
